# Generated by Django 5.1.4 on 2024-12-31 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelapp', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_rooms', models.FloatField(default=0.0)),
                ('no_of_people', models.IntegerField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('total_price', models.FloatField(default=0.0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.hotel')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
    ]
