# Generated by Django 5.1.4 on 2025-01-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
