# Generated by Django 5.1.4 on 2024-12-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('contactNo', models.CharField(max_length=15)),
                ('govId', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
